apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: taskapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: taskapp/mongodb
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: taskapp/mongodb
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: MONGO_URI
      remoteRef:
        key: taskapp/mongodb
        property: MONGO_URI
